### PR TITLE
feat!(run): migrate gradual rollout sample to v2 Cloud Run resource

### PR DESCRIPTION
**Pull request by ace-n**
Example PR, please 🚨🚨🚨 **DO NOT MERGE** 🚨🚨🚨

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@ace-n
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@ace-n
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by betsy-lichtenberg** [comment]
Getting this error:

```
 Error: Error waiting to create Service: Error waiting for Creating Service: Error code 13, message: Revision 'cloudrun-srv-green' does not exist or is deleted. Update all traffic to route to currently available revisions.
│
│   with google_cloud_run_v2_service.default,
│   on main.tf line 18, in resource "google_cloud_run_v2_service" "default":
│   18: resource "google_cloud_run_v2_service" "default" {
```

**Comment by comment-bot-dev** [comment]
@ace-n
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Pull request closed without merging**
