### PR TITLE
docs: Update GMK resource examples now that Clusters and Topic resources are GA

### PR DESCRIPTION
**Pull request by jessdejong**
## Description

GMK Clusters and Topics are getting promoted to GA after the submission of https://github.com/GoogleCloudPlatform/magic-modules/pull/12264. We need to update our public documentation to use our GA resources instead of the google-beta ones. Issue: https://b.corp.google.com/issues/377724373

## Checklist

**Readiness**

- Please approve this PR, but **wait submit after https://github.com/GoogleCloudPlatform/magic-modules/pull/12264 is submitted**.

**Style**

- [x] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [x] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [x] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [x] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [x] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s): https://cloud.google.com/managed-service-for-apache-kafka/docs/create-cluster#create

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

- [x] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [x] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

### CODE REVIEW

**Comment by jessdejong** [comment]
This may need (but I might not be able to successfully trigger this).

/gcbrun

**Review by johndee7310 — APPROVED** [review]
LGTM! Ship it for GA

**Review by glasnt — APPROVED** [review]

**Comment by glasnt** [comment]
```
Error: Error creating Cluster: googleapi: Error 404: Resource "projects/261919062524/regions/us-central1/subnetworks/default" was not found
```

This isn't being specifically created in the sample, but I'm not sure if it should exist in the project. You could either use the resource to create the subnetwork specifically, or use the data resource to pull the existing information (https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_subnetwork). 

I'll /gcbrun it again to confirm it's not a temporary issue (previous issues were "internal errors", this is something specific)

**Comment by jessdejong** [comment]
"default" subnetworks should exist in the project as long as the compute API is enabled. But I checked and the project with project number "261919062524" is being deleted or already has been deleted.

**Comment by jessdejong** [comment]
The tests should be running, now that I've updated the Cluster and Topic samples to make their own subnets with the `google_compute_subnetwork` resource.

**Comment by jessdejong** [comment]
Please let me know if there's anything else that I can do!

**Comment by jessdejong** [comment]
Hi, I'm not able to see what went wrong in the latest CI test. Could someone give me some insights so I can try and fix the errors?

**Comment by jessdejong** [comment]
@glasnt My team would like to include the project field on the `google_managed_kafka_cluster` and `google_managed_kafka_topic` resource samples. I have already committed these changes, but given that this might not be standard practice (@apeabody), I would like you to take a look at this again if possible. We decided to include the project field in b/377892703.

**Pull request merged**
