### PR TITLE
Added region tags

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Planning to add sample here:

https://cloud.google.com/certificate-manager/docs/dns-authorizations

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by gericdong — COMMENTED** [review]
The start and the end tags for the following two tags don't seem matched.
certificatemanager_map
certificatemanager_map_entry_one

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by gericdong — APPROVED** [review]
LGTM

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by betsy-lichtenberg** [comment]
Tests pass for this example:

Step #4 - "test-samples-3":     --- PASS: TestSamples/3/dns_managed_zone_with_wildcard_certificate

**Pull request merged**
