### PR TITLE
chore(cloudsql): code clean up

### PR DESCRIPTION
**Pull request by msampathkumar**
These code samples are redundant. Similar samples can be found in db prefix folder  code samples. (mysql_, postgres_, sqlserver_ folder under cloud_sql parent folder)

## Description

Related to https://github.com/terraform-google-modules/terraform-docs-samples/issues/440

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

Updates for Cloud Docs are at cl/553758056, cl/554790268

### CODE REVIEW

**Comment by enocom** [comment]
@msampathkumar is there a corresponding CL for updating the docs internally? As is, this will break our public docs.

**Comment by msampathkumar** [comment]
> @msampathkumar is there a corresponding CL for updating the docs internally? As is, this will break our public docs.

Thank you for your prompt response. I have CL at [cl/553758056](http://cl/553758056)

**Comment by enocom** [comment]
Looks like snippet-bot check is still upset. Let's get that passing and then ping me here and I'll approve.

**Comment by msampathkumar** [comment]
Working on second cl/554790268

**Comment by enocom** [comment]
Just let me know when you're ready for another pass.

**Review by enocom — APPROVED** [review]

**Review by rogerthatdev — APPROVED** [review]

**Pull request merged**
