### PR TITLE
fix(cloud_run): add deletion_protection

### PR DESCRIPTION
**Pull request by apeabody**
Add `deletion_protection = false` for `google_cloud_run_v2_service` for TPGv6

In partial resolution of https://github.com/terraform-google-modules/terraform-docs-samples/issues/740

### CODE REVIEW

**Comment by apeabody** [comment]
@glasnt - Looks like there are a few other issues (e.g. `google_vpc_access_connector`), but this is good starting point.

**Comment by glasnt** [comment]
@apeabody a lot of these were added in #739 which wasn't merged until after the last periodic. 

I didn't add `deletion_protection` to the samples in this PR because they aren't tested, so don't need to have this. But strictly speaking your PR is correct, all samples should have this argument for completeness.

**Review by glasnt — APPROVED** [review]
Other samples use "# set to "true" in production", but this comment is also fine

**Comment by apeabody** [comment]
> Other samples use "# set to "true" in production", but this comment is also fine

Thanks @glasnt - Let me know if you would like me to open a PR to replace everywhere, I also copied this syntax from the repo.

**Comment by apeabody** [comment]
> @apeabody a lot of these were added in #739 which wasn't merged until after the last periodic.
> 
> I didn't add `deletion_protection` to the samples in this PR because they aren't tested, so don't need to have this. But strictly speaking your PR is correct, all samples should have this argument for completeness.

Gotcha - Yeah, after seeing a few in the test I decided to all to all the `google_cloud_run_v2_service`.  To your point this will reduce friction for those following the documentation.

**Pull request merged**
