### PR TITLE
feat: New Service agent sample for IAM

### PR DESCRIPTION
**Pull request by melaniedejong**
## Description

Adds terraform samples for service agent creation, to be used in the IAM documentation (https://cloud.google.com/iam/docs).

## Checklist

**Readiness**

- [x] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**

- [X] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [X] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [X] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [X] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [X] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [X] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s): Doc not yet published, but will be in the IAM doc set

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

N/A

### CODE REVIEW

**Comment by melaniedejong** [comment]
Can you help me understand why these tests are failing and what I need to do to fix them?

**Comment by msampathkumar** [comment]
Hi @melaniedejong 

I found minor lint-errors

Error: No newline at end of file ./iam/create_service_agent/main.tf
Error: No newline at end of file ./iam/create_service_agent/test.yaml

besides this, there seem to some CICD error!

@bharathkkb I see `Error: Failed to install provider` can you advice on this ?
Log file https://pantheon.corp.google.com/cloud-build/builds/78cfc1da-4edf-405e-832e-08b30800dd0f;step=4?project=cloud-foundation-cicd

**Comment by msampathkumar** [comment]
We got an update from bharathkkb. This is an issue with CICD provider installation, we will be fixing it soon.

**Comment by melaniedejong** [comment]
Got it, thank you!

I also learned some new information that will require me to tweak this sample. Please hold off on review until I make those changes.

**Comment by msampathkumar** [comment]
@melaniedejong sure. I have added `waiting-response` label to this PR. Please clear this label, once this PR is review-ready.

JLYK, the CICD issues I mentioned earlier is now fixed.

**Comment by melaniedejong** [comment]
Ready for review! I don't think I have permission to remove the label, unfortunately.

**Comment by msampathkumar** [comment]
/gcbrun

Update the PR to latest changes, re-run the tests & enable auto-merge.

**Review by msampathkumar — APPROVED** [review]
LGTM

**Pull request merged**
