### PR TITLE
fix(run): replace `automatic` with `auto` param in secrets resources

### PR DESCRIPTION
**Pull request by rogerthatdev**
With v5.0.0 of the Google provider, the parameter `automatic` for the [`google_secret_manager_secret` resource](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/secret_manager_secret) has been deprecated in favor of the `auto` parameter. This PR replaces its use in 2 Cloud Run samples

### CODE REVIEW

**Comment by msampathkumar** [comment]
Nice work @rogerthatdev

**Comment by msampathkumar** [comment]
sqlserver_instance_cmek samples is having KMS error(keyring-name already exists)

**Comment by rogerthatdev** [comment]
> sqlserver_instance_cmek samples is having KMS error(keyring-name already exists)

This sample is not included in this PR. The int test may be failing because it is trying to deploy two identically named resources from 2 different samples.

**Review by glasnt — APPROVED** [review]

**Comment by rogerthatdev** [comment]
int tests are failing due to unrelated test failures.  Merging this CL and bypassing branch protections.

**Pull request merged**
