### PR TITLE
fix(sql): Removed failover_target from postgres_instance_replica.

### PR DESCRIPTION
**Pull request by ibhaskar2**
## Description
PG doesn't support setting a replica as failover_target. Even setting it to 'false' doesn't cause any issue but creates confusion. So removed it from here. Context - b/290620351

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

## Checklist

**Readiness**

- [X] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**

- [X] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ ] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [X] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [X] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [X] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [X] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s): https://cloud.google.com/sql/docs/postgres/replication/create-replica#terraform

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

- [X] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [X] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

### CODE REVIEW

**Comment by msampathkumar** [comment]
Conventionalcommits.org check failed with following message.

Visit [conventionalcommits.org](https://conventionalcommits.org/) to learn our conventions.

Run `git commit --amend` and edit your message to match Conventional Commit guidelines.

**Comment by ibhaskar2** [comment]
Done

**Review by msampathkumar — APPROVED** [review]
LGTM.

All tests are passing.

**Comment by msampathkumar** [comment]
As per the users PR description. Merging the PR.

**Pull request merged**
