### PR TITLE
Removed dashes from any resources names and replaced with _

### PR DESCRIPTION
**Pull request by betsy-lichtenberg**
Fix for https://github.com/terraform-google-modules/terraform-docs-samples/issues/146

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
./cloudfunctions2_basic_auditlogs/main.tf:137:      value     = "/projects/_/buckets/${google_storage_bucket.audit_log_bucket.name}/objects/*.txt" # Path pattern selects 
Error: Trailing whitespace found in the lines above.
Checking for missing newline at end of file
 ``` 
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
╷
│
 
Error: 
Argument or block definition required
│
 
│
 
  on cloudfunctions2_basic_auditlogs/main.tf line 138, in resource "google_cloudfunctions2_function" "function":
│
 
 138: 
all
 .txt files in the bucket
│
 
│
 
An argument or block definition is required here. To set an argument, use
│
 
the equals sign "=" to introduce the argument value.
╵
Error: terraform fmt failed with exit code 2
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
cloudfunctions2_basic_auditlogs/main.tf
--- old/cloudfunctions2_basic_auditlogs/main.tf
+++ new/cloudfunctions2_basic_auditlogs/main.tf
@@ -135,9 +135,9 @@
     event_filters {
       attribute = "resourceName"
       # Selects all .txt files in the bucket
-      value     = "/projects/_/buckets/${google_storage_bucket.audit_log_bucket.name}/objects/*.txt"
+      value = "/projects/_/buckets/${google_storage_bucket.audit_log_bucket.name}/objects/*.txt"
       # Allows path patterns to be used in the value field
-      operator  = "match-path-pattern"
+      operator = "match-path-pattern"
     }
   }
 }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate ./cloud_run_service_add_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_configuration
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_connect_cloud_sql
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_custom_domain_mapping
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_deploy_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_image_processing
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_ingress
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_interservice
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_multiple_regions
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_noauth
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_pubsub
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_remove_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_scheduled
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_secure_services
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_static_outbound
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_tasks
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_gradual_rollout
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_latest_revision
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_rollback
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_split
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_split_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_system_packages
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_basic
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_basic_auditlogs
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_basic_gcs
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_full
Success!
 The configuration is valid.
terraform_validate ./cloudrun_service_access_control
Success!
 The configuration is valid.
terraform_validate ./cloudrun_service_identity
Success!
 The configuration is valid.
terraform_validate ./cloudrun_vpc_access_connector
Success!
 The configuration is valid.
terraform_validate ./composer_multi_project_monitoring
Success!
 The configuration is valid.
terraform_validate ./compute_packet_mirroring_full
Success!
 The configuration is valid.
terraform_validate ./compute_reservation
Success!
 The configuration is valid.
terraform_validate ./compute_run_shutdown_scripts
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_basic
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_private
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_private_forwarding
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_private_peering
╷
│
 
Error: 
Reference to undeclared resource
│
 
│
 
  on main.tf line 27, in resource "google_dns_managed_zone" "peering_zone":
│
 
  27:       network_url = 
google_compute_network.network-source
.id
│
 
│
 
A managed resource "google_compute_network" "network-source" has not been
│
 
declared in the root module.
╵
╷
│
 
Error: 
Reference to undeclared resource
│
 
│
 
  on main.tf line 33, in resource "google_dns_managed_zone" "peering_zone":
│
 
  33:       network_url = 
google_compute_network.network-target
.id
│
 
│
 
A managed resource "google_compute_network" "network-target" has not been
│
 
declared in the root module.
╵
terraform_validate ./dns_managed_zone_quickstart
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_service_directory
Success!
 The configuration is valid.
terraform_validate ./dns_policy_basic
╷
│
 
Error: 
Reference to undeclared resource
│
 
│
 
  on main.tf line 35, in resource "google_dns_policy" "example_policy":
│
 
  35:     network_url = 
google_compute_network.network-1
.id
│
 
│
 
A managed resource "google_compute_network" "network-1" has not been
│
 
declared in the root module.
╵
╷
│
 
Error: 
Reference to undeclared resource
│
 
│
 
  on main.tf line 38, in resource "google_dns_policy" "example_policy":
│
 
  38:     network_url = 
google_compute_network.network-2
.id
│
 
│
 
A managed resource "google_compute_network" "network-2" has not been
│
 
declared in the root module.
╵
terraform_validate ./dns_record_set_basic
Success!
 The configuration is valid.
terraform_validate ./dns_response_policy_basic
Success!
 The configuration is valid.
terraform_validate ./dns_response_policy_rule_basic
Success!
 The configuration is valid.
terraform_validate ./eventarc_basic_tf
Success!
 The configuration is valid.
terraform_validate ./eventarc_workflows
Success!
 The configuration is valid.
terraform_validate ./external_cdn_lb_with_backend_bucket
Success!
 The configuration is valid.
terraform_validate ./external_http_lb_bucket_backend
Success!
 The configuration is valid.
terraform_validate ./external_http_lb_mig_backend
Success!
 The configuration is valid.
terraform_validate ./external_http_lb_mig_backend_custom_header
Success!
 The configuration is valid.
terraform_validate ./external_ssl_proxy_lb_mig_backend
Success!
 The configuration is valid.
terraform_validate ./external_ssl_proxy_lb_mig_backend_custom_header
Success!
 The configuration is valid.
terraform_validate ./external_tcp_proxy_lb_mig_backend
Success!
 The configuration is valid.
terraform_validate ./external_tcp_proxy_lb_mig_backend_custom_header
Success!
 The configuration is valid.
terraform_validate ./external_vpn_gateway
Success!
 The configuration is valid.
terraform_validate ./firewall_with_target_tags
Success!
 The configuration is valid.
terraform_validate ./flask_google_cloud_quickstart
Success!
 The configuration is valid.
terraform_validate ./ha_vpn_gateway_gcp_to_gcp
Success!
 The configuration is valid.
terraform_validate ./health-check-tcp
Success!
 The configuration is valid.
terraform_validate ./instance_custom_hostname
Success!
 The configuration is valid.
terraform_validate ./instance_virtual_display_enabled
Success!
 The configuration is valid.
terraform_validate ./int_https_lb_https_redirect
Success!
 The configuration is valid.
terraform_validate ./internal_http_lb_with_mig_backend
Success!
 The configuration is valid.
terraform_validate ./internal_tcp_udp_lb_with_mig_backend
Success!
 The configuration is valid.
terraform_validate ./media_cdn_keyset
Success!
 The configuration is valid.
terraform_validate ./media_cdn_quickstart
Success!
 The configuration is valid.
terraform_validate ./network_custom_mtu
Success!
 The configuration is valid.
terraform_validate ./network_management_connectivity_test_addresses
Success!
 The configuration is valid.
terraform_validate ./network_management_connectivity_test_instances
Success!
 The configuration is valid.
terraform_validate ./os_login
Success!
 The configuration is valid.
terraform_validate ./private_service_connect_google_apis
Success!
 The configuration is valid.
terraform_validate ./privateca_capool_all_fields
Success!
 The configuration is valid.
terraform_validate ./privateca_capool_basic
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_authority_basic
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_authority_byo_key
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_authority_subordinate
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_config
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_csr
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_no_authority
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_with_template
Success!
 The configuration is valid.
terraform_validate ./privateca_quickstart
Success!
 The configuration is valid.
terraform_validate ./region_autoscaler_basic
Success!
 The configuration is valid.
terraform_validate ./regional-external-http-load-balancer
Success!
 The configuration is valid.
terraform_validate ./regional_external_http_load_balancer
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_http_ilb_with_mig_backend
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_http_ilb_with_mig_backend_basic_example
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_http_ilb_with_mig_backend_cross_reference_example
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_https_ilb_with_mig_backend_basic_example
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_https_ilb_with_mig_backend_cross_reference_example
Success!
 The configuration is valid.
terraform_validate ./spot_instance_basic
Success!
 The configuration is valid.
terraform_validate ./sql_database_basic
Success!
 The configuration is valid.
terraform_validate ./sql_database_instance_my_sql
Success!
 The configuration is valid.
terraform_validate ./sql_database_instance_postgres
Success!
 The configuration is valid.
terraform_validate ./sql_database_instance_sqlserver
Success!
 The configuration is valid.
terraform_validate ./sql_instance_cmek
Success!
 The configuration is valid.
terraform_validate ./sql_instance_ha
Success!
 The configuration is valid.
terraform_validate ./sql_instance_iam_condition
Success!
 The configuration is valid.
terraform_validate ./sql_instance_labels
Success!
 The configuration is valid.
terraform_validate ./sql_instance_pitr
Success!
 The configuration is valid.
terraform_validate ./sql_instance_ssl_cert
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_authorized_network
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_backup
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_backup_location
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_backup_retention
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_clone
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_flags
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_private_ip
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_public_ip
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_pvp
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_replica
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_ssm
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_authorized_network
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_backup
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_backup_location
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_backup_retention
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_clone
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_flags
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_private_ip
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_public_ip
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_pvp
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_replica
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_ssm
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_active_directory
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_authorized_network
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_backup
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_backup_location
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_backup_retention
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_clone
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_flags
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_private_ip
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_public_ip
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_replica
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_ssm
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_vm_instance
Success!
 The configuration is valid.
terraform_validate ./storage_hmac_key
Success!
 The configuration is valid.
terraform_validate ./storage_make_data_public
Success!
 The configuration is valid.
terraform_validate ./storage_new_bucket
Success!
 The configuration is valid.
terraform_validate ./storage_object_lifecycle_setting
Success!
 The configuration is valid.
terraform_validate ./storage_pubsub_notifications
Success!
 The configuration is valid.
terraform_validate ./storage_static_website
Success!
 The configuration is valid.
terraform_validate ./target_grpc_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_http_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_http_proxy_https_redirect
Success!
 The configuration is valid.
terraform_validate ./target_https_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_ssl_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_tcp_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
terraform_validate ./url_map_bucket_and_service
Success!
 The configuration is valid.
terraform_validate ./url_map_header_based_routing
Success!
 The configuration is valid.
terraform_validate ./url_map_parameter_based_routing
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_path
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_path_partial
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_route
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_route_partial
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_dataset
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_featurestore
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_managed_notebooks_runtime
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_metadata_store
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_user_managed_notebooks_instance
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate ./cloud_run_service_add_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_configuration
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_connect_cloud_sql
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_custom_domain_mapping
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_deploy_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_image_processing
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_ingress
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_interservice
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_multiple_regions
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_noauth
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_pubsub
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_remove_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_scheduled
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_secure_services
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_static_outbound
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_tasks
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_gradual_rollout
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_latest_revision
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_rollback
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_split
Success!
 The configuration is valid.
terraform_validate ./cloud_run_service_traffic_split_tag
Success!
 The configuration is valid.
terraform_validate ./cloud_run_system_packages
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_basic
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_basic_auditlogs
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_basic_gcs
Success!
 The configuration is valid.
terraform_validate ./cloudfunctions2_full
Success!
 The configuration is valid.
terraform_validate ./cloudrun_service_access_control
Success!
 The configuration is valid.
terraform_validate ./cloudrun_service_identity
Success!
 The configuration is valid.
terraform_validate ./cloudrun_vpc_access_connector
Success!
 The configuration is valid.
terraform_validate ./composer_multi_project_monitoring
Success!
 The configuration is valid.
terraform_validate ./compute_packet_mirroring_full
Success!
 The configuration is valid.
terraform_validate ./compute_reservation
Success!
 The configuration is valid.
terraform_validate ./compute_run_shutdown_scripts
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_basic
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_private
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_private_forwarding
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_private_peering
╷
│
 
Error: 
Reference to undeclared resource
│
 
│
 
  on main.tf line 27, in resource "google_dns_managed_zone" "peering_zone":
│
 
  27:       network_url = 
google_compute_network.network-source
.id
│
 
│
 
A managed resource "google_compute_network" "network-source" has not been
│
 
declared in the root module.
╵
╷
│
 
Error: 
Reference to undeclared resource
│
 
│
 
  on main.tf line 33, in resource "google_dns_managed_zone" "peering_zone":
│
 
  33:       network_url = 
google_compute_network.network-target
.id
│
 
│
 
A managed resource "google_compute_network" "network-target" has not been
│
 
declared in the root module.
╵
terraform_validate ./dns_managed_zone_quickstart
Success!
 The configuration is valid.
terraform_validate ./dns_managed_zone_service_directory
Success!
 The configuration is valid.
terraform_validate ./dns_policy_basic
Success!
 The configuration is valid.
terraform_validate ./dns_record_set_basic
Success!
 The configuration is valid.
terraform_validate ./dns_response_policy_basic
Success!
 The configuration is valid.
terraform_validate ./dns_response_policy_rule_basic
Success!
 The configuration is valid.
terraform_validate ./eventarc_basic_tf
Success!
 The configuration is valid.
terraform_validate ./eventarc_workflows
Success!
 The configuration is valid.
terraform_validate ./external_cdn_lb_with_backend_bucket
Success!
 The configuration is valid.
terraform_validate ./external_http_lb_bucket_backend
Success!
 The configuration is valid.
terraform_validate ./external_http_lb_mig_backend
Success!
 The configuration is valid.
terraform_validate ./external_http_lb_mig_backend_custom_header
Success!
 The configuration is valid.
terraform_validate ./external_ssl_proxy_lb_mig_backend
Success!
 The configuration is valid.
terraform_validate ./external_ssl_proxy_lb_mig_backend_custom_header
Success!
 The configuration is valid.
terraform_validate ./external_tcp_proxy_lb_mig_backend
Success!
 The configuration is valid.
terraform_validate ./external_tcp_proxy_lb_mig_backend_custom_header
Success!
 The configuration is valid.
terraform_validate ./external_vpn_gateway
Success!
 The configuration is valid.
terraform_validate ./firewall_with_target_tags
Success!
 The configuration is valid.
terraform_validate ./flask_google_cloud_quickstart
Success!
 The configuration is valid.
terraform_validate ./ha_vpn_gateway_gcp_to_gcp
Success!
 The configuration is valid.
terraform_validate ./health-check-tcp
Success!
 The configuration is valid.
terraform_validate ./instance_custom_hostname
Success!
 The configuration is valid.
terraform_validate ./instance_virtual_display_enabled
Success!
 The configuration is valid.
terraform_validate ./int_https_lb_https_redirect
Success!
 The configuration is valid.
terraform_validate ./internal_http_lb_with_mig_backend
Success!
 The configuration is valid.
terraform_validate ./internal_tcp_udp_lb_with_mig_backend
Success!
 The configuration is valid.
terraform_validate ./media_cdn_keyset
Success!
 The configuration is valid.
terraform_validate ./media_cdn_quickstart
Success!
 The configuration is valid.
terraform_validate ./network_custom_mtu
Success!
 The configuration is valid.
terraform_validate ./network_management_connectivity_test_addresses
Success!
 The configuration is valid.
terraform_validate ./network_management_connectivity_test_instances
Success!
 The configuration is valid.
terraform_validate ./os_login
Success!
 The configuration is valid.
terraform_validate ./private_service_connect_google_apis
Success!
 The configuration is valid.
terraform_validate ./privateca_capool_all_fields
Success!
 The configuration is valid.
terraform_validate ./privateca_capool_basic
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_authority_basic
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_authority_byo_key
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_authority_subordinate
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_config
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_csr
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_no_authority
Success!
 The configuration is valid.
terraform_validate ./privateca_certificate_with_template
Success!
 The configuration is valid.
terraform_validate ./privateca_quickstart
Success!
 The configuration is valid.
terraform_validate ./region_autoscaler_basic
Success!
 The configuration is valid.
terraform_validate ./regional-external-http-load-balancer
Success!
 The configuration is valid.
terraform_validate ./regional_external_http_load_balancer
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_http_ilb_with_mig_backend
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_http_ilb_with_mig_backend_basic_example
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_http_ilb_with_mig_backend_cross_reference_example
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_https_ilb_with_mig_backend_basic_example
Success!
 The configuration is valid.
terraform_validate ./shared_vpc_https_ilb_with_mig_backend_cross_reference_example
Success!
 The configuration is valid.
terraform_validate ./spot_instance_basic
Success!
 The configuration is valid.
terraform_validate ./sql_database_basic
Success!
 The configuration is valid.
terraform_validate ./sql_database_instance_my_sql
Success!
 The configuration is valid.
terraform_validate ./sql_database_instance_postgres
Success!
 The configuration is valid.
terraform_validate ./sql_database_instance_sqlserver
Success!
 The configuration is valid.
terraform_validate ./sql_instance_cmek
Success!
 The configuration is valid.
terraform_validate ./sql_instance_ha
Success!
 The configuration is valid.
terraform_validate ./sql_instance_iam_condition
Success!
 The configuration is valid.
terraform_validate ./sql_instance_labels
Success!
 The configuration is valid.
terraform_validate ./sql_instance_pitr
Success!
 The configuration is valid.
terraform_validate ./sql_instance_ssl_cert
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_authorized_network
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_backup
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_backup_location
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_backup_retention
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_clone
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_flags
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_private_ip
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_public_ip
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_pvp
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_replica
Success!
 The configuration is valid.
terraform_validate ./sql_mysql_instance_ssm
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_authorized_network
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_backup
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_backup_location
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_backup_retention
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_clone
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_flags
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_private_ip
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_public_ip
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_pvp
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_replica
Success!
 The configuration is valid.
terraform_validate ./sql_postgres_instance_ssm
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_active_directory
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_authorized_network
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_backup
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_backup_location
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_backup_retention
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_clone
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_flags
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_private_ip
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_public_ip
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_replica
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_instance_ssm
Success!
 The configuration is valid.
terraform_validate ./sql_sqlserver_vm_instance
Success!
 The configuration is valid.
terraform_validate ./storage_hmac_key
Success!
 The configuration is valid.
terraform_validate ./storage_make_data_public
Success!
 The configuration is valid.
terraform_validate ./storage_new_bucket
Success!
 The configuration is valid.
terraform_validate ./storage_object_lifecycle_setting
Success!
 The configuration is valid.
terraform_validate ./storage_pubsub_notifications
Success!
 The configuration is valid.
terraform_validate ./storage_static_website
Success!
 The configuration is valid.
terraform_validate ./target_grpc_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_http_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_http_proxy_https_redirect
Success!
 The configuration is valid.
terraform_validate ./target_https_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_ssl_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./target_tcp_proxy_basic
Success!
 The configuration is valid.
terraform_validate ./test/setup
Success!
 The configuration is valid.
terraform_validate ./url_map_bucket_and_service
Success!
 The configuration is valid.
terraform_validate ./url_map_header_based_routing
Success!
 The configuration is valid.
terraform_validate ./url_map_parameter_based_routing
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_path
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_path_partial
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_route
Success!
 The configuration is valid.
terraform_validate ./url_map_traffic_director_route_partial
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_dataset
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_featurestore
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_managed_notebooks_runtime
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_metadata_store
Success!
 The configuration is valid.
terraform_validate ./vertex_ai_user_managed_notebooks_instance
Success!
 The configuration is valid.
 ```

**Comment by comment-bot-dev** [comment]
@betsy-lichtenberg
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by bharathkkb — APPROVED** [review]

**Pull request merged**
