### PR TITLE
Add provider requirement to functions v2 to make error message more obvious

### PR DESCRIPTION
**Pull request by gleichda**
This will add the minimum required version in order to make potential errors more obvious:
Before:
```bash
Error: Invalid resource type

  on main.tf line 27, in resource "google_cloudfunctions2_function" "function":
  27: resource "google_cloudfunctions2_function" "function" {

The provider hashicorp/google does not support resource type "google_cloudfunctions2_function". Did you mean "google_cloudfunctions_function"?
```

After:
```bash
Error: Inconsistent dependency lock file

The following dependency selections recorded in the lock file are inconsistent with the current configuration:
  - provider registry.terraform.io/hashicorp/google: locked version selection 4.32.0 doesn't match the updated version constraints ">= 4.34.0"

To update the locked dependency selections to match a changed configuration, run:
  terraform init -upgrade
```

### CODE REVIEW

**Comment by timbohiatt** [comment]
+1 to this PR. 
Personally had this issue, hence @gleichda has raised the PR. Took quite some time to realise I had inconsistent versions with the google and google-beta providers. For users who are using old providers this would resolve the issue immediately for them.

**Review by bharathkkb — APPROVED** [review]
LGTM

@betsy-lichtenberg Is this something we should add to the samples guide as a recommendation? Something along the lines of `Add a minimum required constraint for the TPG/B version for new resource samples.`

**Comment by betsy-lichtenberg** [comment]
I think the easiest way to avoid version issues is to do testing in Cloud Shell because Terraform is built in. Or am I misunderstanding the issue?

**Comment by bharathkkb** [comment]
This is for the [terraform provider version](https://github.com/hashicorp/terraform-provider-google/blob/main/CHANGELOG.md) and only occurs when users copy paste samples into existing configurations where the provider info is captured in a lock file. For users trying it out via cloud shell min version is not needed (although does not hurt).

**Comment by betsy-lichtenberg** [comment]
OK, I'm open to adding guidance on this. Please file a bug in buganizer componentid:1156592.

**Pull request merged**
