### PR TITLE
Add IAM Deny policy snippet

### PR DESCRIPTION
**Pull request by msampathkumar**
Adding TF Snippet at https://cloud.google.com/iam/docs/deny-access#create-deny-policy

For more details, please check http://b/233721480

Request for reviewers: If allowed, please update path from `iam_create_deny_policy/main.tf` to `iam/iam_create_deny_policy/main.tf` (i.e. Using separate folder for IAM snippets) or advice as such.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
iam_create_deny_policy/main.tf
--- old/iam_create_deny_policy/main.tf
+++ new/iam_create_deny_policy/main.tf
@@ -36,7 +36,7 @@
   display_name = "My deny policy."
   rules {
     deny_rule {
-      denied_principals = ["principal://iam.googleapis.com/projects/-/serviceAccounts/${google_service_account.default.email}"]
+      denied_principals  = ["principal://iam.googleapis.com/projects/-/serviceAccounts/${google_service_account.default.email}"]
       denied_permissions = ["iam.googleapis.com/roles.create"]
     }
   }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by betsy-lichtenberg** [comment]
>>Request for reviewers: If allowed, please update path from iam_create_deny_policy/main.tf to iam/iam_create_deny_policy/main.tf (i.e. Using separate folder for IAM snippets) or advice as such.


This should be fine, but you might want to confirm with itseric@ and rogerthatdev@

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by msampathkumar** [comment]
Update: For now dropping the idea of updating path to iam/iam_create_deny_policy/main.tf

Please check and merge PR

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by betsy-lichtenberg** [comment]
I'm getting this error when I try to run the sample:

```
Error: Error creating DenyPolicy: googleapi: Error 403: Permission iam.googleapis.com/denypolicies.create denied on resource cloudresourcemanager.googleapis.com/projects/subtle-abacus-220417
│
│   with google_iam_deny_policy.default,
│   on main.tf line 12, in resource "google_iam_deny_policy" "default":
│   12: resource "google_iam_deny_policy" "default" {
```

Maybe try adding permission settings to the sample?

**Comment by msampathkumar** [comment]
Hi @betsy-lichtenberg please check this - https://screenshot.googleplex.com/87bDrRwfUXaGKrb

"Deny Admin" IAM role is not available at Project level.

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by betsy-lichtenberg** [comment]
Sampath,

Please see https://cloud.google.com/iam/docs/troubleshooting-deny. If that doesn't help, talk to jefesaurus@

**Comment by comment-bot-dev** [comment]
@msampathkumar
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_whitespace
 Failed whitespace check. More details below. 
 ```bash 
Checking for trailing whitespace
Checking for missing newline at end of file
Error: No newline at end of file ./cloud_run_healthchecks_startup_probe_http/main.tf
 ```

**Review by betsy-lichtenberg — APPROVED** [review]

**Pull request merged**
