### PR TITLE
feat: Add GKE Autopilot Basic and Release Channel

### PR DESCRIPTION
**Pull request by apeabody**
## Description

Fixes b/323964446

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

## Checklist

**Readiness**

- [x] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**

- [x] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [x] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [x] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [x] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [x] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s):
  - https://cloud.google.com/kubernetes-engine/docs/how-to/creating-an-autopilot-cluster

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

- [x] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [x] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

### CODE REVIEW

**Comment by glasnt** [comment]
I know this PR is not yet ready, but it looks like changes in default deletion_protection in the resource are causing CI failures: 

> On version 5.0.0+ of the provider, you must explicitly set deletion_protection=false (and run terraform apply to write the field to state) in order to destroy a cluster. It is recommended to not set this field (or set it to true) until you're ready to destroy.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster

Cloud SQL refers to this setting a lot, and also adds inline comments that might be useful to borrow from: 

```
  # set `deletion_protection` to true, will ensure that one cannot accidentally delete this instance by
  # use of Terraform whereas `deletion_protection_enabled` flag protects this instance at the GCP level.
  deletion_protection = false
```

**Comment by apeabody** [comment]
> I know this PR is not yet ready, but it looks like changes in default deletion_protection in the resource are causing CI failures:
> 
> > On version 5.0.0+ of the provider, you must explicitly set deletion_protection=false (and run terraform apply to write the field to state) in order to destroy a cluster. It is recommended to not set this field (or set it to true) until you're ready to destroy.
> 
> https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster
> 
> Cloud SQL refers to this setting a lot, and also adds inline comments that might be useful to borrow from:
> 
> ```
>   # set `deletion_protection` to true, will ensure that one cannot accidentally delete this instance by
>   # use of Terraform whereas `deletion_protection_enabled` flag protects this instance at the GCP level.
>   deletion_protection = false
> ```

Hey @glasnt! Yeah, I was thinking to ideally not include `deletion_protection = false` in the actual sample and modify the value later in the integration test. However I like you suggestion of including a comment, which is certainly much simpler. :)

**Comment by glasnt** [comment]
This PR is pending upstream changes, as discussed with the author. Marking as "do-not-merge" until those are resolved.

**Review by glasnt — APPROVED** [review]

**Comment by glasnt** [comment]
I can't merge this as I'm not in the terraform-samples-git-admins team

**Pull request merged**
